[global]
color_cycle = [
  "#4E79A7", # blue
  "#F28E2B", # orange
  "#E15759", # red
  "#76B7B2", # teal
  "#59A14F", # green
  "#EDC948", # yellow
  "#B07AA1", # purple
  "#FF9DA7", # pink
]
color_palette_expanded = [
  "#4E79A7", # blue
  "#F28E2B", # orange
  "#E15759", # red
  "#76B7B2", # teal
  "#59A14F", # green
  "#EDC948", # yellow
  "#B07AA1", # purple
  "#FF9DA7", # pink
  "#9C755F", # brown
  "#7F3C8D", # violet
  "#11A579", # emerald
  "#3969AC", # cobalt
  "#F2B701", # gold
  "#E73F74", # magenta
  "#80BA5A", # lime
  "#E68310", # amber
]
restcolor = "#BBBBBB"
fac_in_inst_color = "#7d7d7d"

subject_groups = [
  "Geisteswissenschaften",
  "Mathematik, Naturwissenschaften",
  "Ingenieurwissenschaften",
  "Wirtschaftswissenschaften",
  "Sozial- und Verhaltenswissenschaften, Sport",
]

[global.faculty_institute_mappings."Fakultät I"]
color = 0

[global.faculty_institute_mappings."Fakultät I".institute_colors]
"Institut für Sprache und Kommunikation" = 0
"Institut für Berufliche Bildung und Arbeitslehre" = 1
"Institut für Kunstwissenschaft und Historische Urbanistik" = 2
"Institut für Philosophie, Literatur-, Wissenschafts- und Technikgeschichte" = 3
"Zentrum für Antisemitismusforschung" = 4
"Institut für Erziehungswissenschaft" = 5
"Zentrum für Interdisziplinäre Frauen- und Geschlechterforschung" = 6

[global.faculty_institute_mappings."Fakultät II"]
color = 1

[global.faculty_institute_mappings."Fakultät II".institute_colors]
"Institut für Chemie" = 0
"Institut für Mathematik" = 1
"Institut für Physik und Astronomie" = 2
"Institut für Festkörperphysik" = 3
"Institut für Optik und Atomare Physik" = 4
"Institut für Theoretische Physik" = 5
"Zentrum für Astronomie und Astrophysik" = 6

[global.faculty_institute_mappings."Fakultät III"]
color = 2

[global.faculty_institute_mappings."Fakultät III".institute_colors]
"Institut für Biotechnologie" = 0
"Institut für Werkstoffwissenschaften und -technologien" = 1
"Institut für Prozess- und Verfahrenstechnik" = 2
"Institut für Technischen Umweltschutz" = 3
"Institut für Energietechnik" = 4
"Institut für Lebensmitteltechnologie und Lebensmittelchemie" = 5

[global.faculty_institute_mappings."Fakultät IV"]
color = 3

[global.faculty_institute_mappings."Fakultät IV".institute_colors]
"Institut für Softwaretechnik und Theoretische Informatik" = 0
"Institut für Energie- und Automatisierungstechnik" = 1
"Institut für Telekommunikationssysteme" = 2
"Institut für Hochfrequenz- und Halbleiter-Systemtechnologien" = 3
"Institut für Technische Informatik und Mikroelektronik" = 4
"Institut für Wirtschaftsinformatik und Quantitative Methoden" = 5

[global.faculty_institute_mappings."Fakultät V"]
color = 4

[global.faculty_institute_mappings."Fakultät V".institute_colors]
"Institut für Werkzeugmaschinen und Fabrikbetrieb" = 0
"Institut für Land- und Seeverkehr" = 1
"Institut für Maschinenkonstruktion und Systemtechnik" = 2
"Institut für Strömungsmechanik und Technische Akustik (ISTA)" = 3
"Institut für Luft- und Raumfahrt" = 4
"Institut für Psychologie und Arbeitswissenschaft" = 5
"Institut für Mechanik" = 6

[global.faculty_institute_mappings."Fakultät VI"]
color = 5

[global.faculty_institute_mappings."Fakultät VI".institute_colors]
"Institut für Architektur" = 0
"Institut für Bauingenieurwesen" = 1
"Institut für Landschaftsarchitektur und Umweltplanung" = 2
"Institut für Soziologie" = 3
"Institut für Stadt- und Regionalplanung" = 4
"Institut für Geodäsie und Geoinformationstechnik" = 5
"Institut für Angewandte Geowissenschaften" = 6
"Institut für Ökologie" = 7

[global.faculty_institute_mappings."Fakultät VII"]
color = 6

[global.faculty_institute_mappings."Fakultät VII".institute_colors]
"Institut für Technologie und Management" = 0
"Institut für Volkswirtschaftlehre und Wirtschaftsrecht" = 1
"Institut für Betriebswirtschaftlehre" = 2

[global.institute_remap]
"Institut für Festkörperphysik" = "Institut für Physik und Astronomie"
"Institut für Optik und Atomare Physik" = "Institut für Physik und Astronomie"
"Institut für Theoretische Physik" = "Institut für Physik und Astronomie"
"Zentrum für Astronomie und Astrophysik" = "Institut für Physik und Astronomie"

[duration_densities]
use_model = false
show_linkedin_and_model = true
ci_threshold = 1000
ci_mode = "double_long_side"
out_folder = "int_plots"
out_name = "total_dur_densities"

[start_densities_anchor]
out_folder = "int_plots"
out_name = "start_densities_anchor"

[start_densities_defense]
out_folder = "int_plots"
out_name = "start_densities_defense"

[duration_densities_from_start_anchor]
use_model = false
show_linkedin_and_model = true
ci_threshold = 1000
ci_mode = "double_long_side"
out_folder = "int_plots"
out_name = "duration_densities_from_start_anchor"

[duration_densities_from_start_defense]
use_model = false
show_linkedin_and_model = true
ci_threshold = 1000
ci_mode = "double_long_side"
out_folder = "int_plots"
out_name = "duration_densities_from_start_defense"

[acc_by_year]
start_year = 2014
end_year = 2025

n_min_institute = 5

out_folder = "int_plots"
out_name = "acceptance_by_year"

[def_by_year]
start_year = 2018
end_year = 2025

n_min_institute = 5

out_folder = "int_plots"
out_name = "defense_by_year"

[study_matrix]
start_year = 2014
end_year = 2025

n_min_categories = 5

out_folder = "int_plots"
out_name = "region_matrix_barplot"

[pbacat_by_year]
start_year = 2014
end_year = 2025

n_min_categories = 5

out_folder = "int_plots"
out_name = "pba_category_by_year"

[country_by_year]
start_year = 2014
end_year = 2025

n_min_categories = 5

out_folder = "int_plots"
out_name = "pba_state_by_year"

[cship_by_year]
start_year = 2014
end_year = 2025

n_min_categories = 5

out_folder = "int_plots"
out_name = "cship_by_year"

[pbacat_pie]
start_year = 2014
end_year = 2025

n_min_institute = 5

out_folder = "int_plots"
out_name = "pba_category"

[pbacat_pie.category_label_names]
TUB = "TU Berlin"
FH = "Fachhochschule"
GER = "Hochschule in Deutschland"
EU = "Hochschule in Europa"
NEU = "Hochschule außerhalb Europas"

[pbastate_pie]
start_year = 2014
end_year = 2025

n_min_institute = 5

out_folder = "int_plots"
out_name = "pba_cat_pie"
[pbastate_pie.category_label_names]
0 = 0

[country_pie]
start_year = 2014
end_year = 2025

n_min_country = 0
n_biggest_countries = 6

out_folder = "int_plots"
out_name = "pba_state"
[country_pie.category_label_names]
0 = 0

[cship_pie]
start_year = 2014
end_year = 2025

n_min_country = 0
n_biggest_countries = 6

out_folder = "int_plots"
out_name = "cship"
[cship_pie.category_label_names]
0 = 0


[gender_by_year_def]
start_year = 2018
end_year = 2025

# die folgenden Parameter werden für die Logik verwendet, um Institute zu entfernen, die zu wenig Daten haben.
min_year_prune = 2020     # das Jahr, ab dem die Logik greift (fruehe Jahre haben generell weniger Daten)
n_min_institutes_abs = 2  # in keinem Jahr darf es weniger Anmeldungen geben als diese Zahl
n_min_institutes_mean = 9 # im Schnitt muss es mindestens so viele Anmeldungen pro Jahr geben

out_folder = "int_plots"
out_name = "gender_defense_by_year"


marker_fac_size = 12
marker_inst_size = 12
marker_total_size = 22
marker_fac_in_inst = 16

width_fac = 4
width_inst = 4
width_total = 12
width_fac_in_inst = 4

[gender_by_year]
start_year = 2014
end_year = 2025

# die folgenden Parameter werden für die Logik verwendet, um Institute zu entfernen, die zu wenig Daten haben.
min_year_prune = 2020     # das Jahr, ab dem die Logik greift (fruehe Jahre haben generell weniger Daten)
n_min_institutes_abs = 6  # in keinem Jahr darf es weniger Anmeldungen geben als diese Zahl
n_min_institutes_mean = 9 # im Schnitt muss es mindestens so viele Anmeldungen pro Jahr geben

out_folder = "int_plots"
out_name = "gender_acceptance_by_year"


marker_fac_size = 12
marker_inst_size = 12
marker_total_size = 22
marker_fac_in_inst = 16

width_fac = 4
width_inst = 4
width_total = 12
width_fac_in_inst = 4


[subject]
start_year = 2014
end_year = 2025

out_folder = "int_plots"
out_name = "sankey_institutes"
link_alpha = 0.7
node_thickness = 100


[subject_overview]
start_year = 2014
end_year = 2025

out_folder = "int_plots"
out_name = "sankey_faculties"

link_alpha = 0.7
node_thickness = 100
